config/routes.rb
Memorypalace::Application.routes.draw do

  resources :fish
  resources :famous_people
  resources :palaces
  resources :pegs

  authenticated :user do
    root :to => 'palaces#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :events

  match 'validate' => "home#validate"
  match "events/:id" => "events#update"

  match "famous_people" => "famous_people#index"
  match "famous_people/code/:code" => "famous_people#code"

  match "famous_people/addpeg/:code" => "famous_people#addpeg"

  match "pegs/add/:fp_id" => "pegs#add"

  match "contact_us" => "contact_us#index"

end

app/models/palace.rb
class Palace < ActiveRecord::Base
  ActiveRecord::Base.include_root_in_json = true
  attr_accessible :title, :ptype, :id, :updated_at, :created_at, :user_id, :peg_id

  belongs_to :user

  has_many :pegs, :order => 'created_at', :dependent => :destroy


end

app/controllers/palaces_controller.rb
class PalacesController < ApplicationController

  before_filter :authenticate_user!, :set_digits

  def set_digits
    @digits = ['OO','OA','OB','OC','OD','OE','OS','OG','OH','ON',
               'AO','AA','AB','AC','AD','AE','AS','AG','AH','AN',
               'BO','BA','BB','BC','BD','BE','BS','BG','BH','BN',
               'CO','CA','CB','CC','CD','CE','CS','CG','CH','CN',
               'DO','DA','DB','DC','DD','DE','DS','DG','DH','DN',
               'EO','EA','EB','EC','ED','EE','ES','EG','EH','EN',
               'SO','SA','SB','SC','SD','SE','SS','SG','SH','SN',
               'GO','GA','GB','GC','GD','GE','GS','GG','GH','GN',
               'HO','HA','HB','HC','HD','HE','HS','HG','HH','HN',
               'NO','NA','NB','NC','ND','NE','NS','NG','NH','NN',]
  end
  #GET /palaces
  # GET /palaces.json
  def index
    puts("> ********")
    puts current_user.id

    @palaces = Palace.find_all_by_user_id(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @palaces }
    end
  end

  # GET /palaces/1
  # GET /palaces/1.json
  def show
    @palace = Palace.find(params[:id])
    session[:current_palace] = @palace.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @palace }
    end
  end

  # GET /palaces/new
  # GET /palaces/new.json
  def new
    @palace = Palace.new(:ptype => 1)
    @palace.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @palace }
    end
  end

  # GET /palaces/1/edit
  def edit
    @palace = Palace.find(params[:id])
  end

  # POST /palaces
  # POST /palaces.json
  def create
    @palace = Palace.new(params[:palace])
    @palace.user_id = current_user.id

    respond_to do |format|
      if @palace.save
        format.html { redirect_to @palace, notice: 'palace was successfully created.' }
        format.json { render json: @palace, status: :created, location: @palace }
      else
        format.html { render action: "new" }
        format.json { render json: @palace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /palaces/1
  # PUT /palaces/1.json
  def update
    @palace = Palace.find(params[:id])

    respond_to do |format|
      if @palace.update_attributes(params[:palace])
        format.html { redirect_to @palace, notice: 'Palace was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @palace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palaces/1
  # DELETE /palaces/1.json
  def destroy
    @palace = Palace.find(params[:id])
    @palace.destroy

    respond_to do |format|
      format.html { redirect_to palaces_url }
      format.json { head :no_content }
    end
  end



end

app/helpers/palaces_helper.rb
module PalacesHelper





end

app/views/palaces/_form.html.erb
<%= simple_form_for(@palace) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <br>
    Type of Palace to create:<br><br>
    <%= f.radio_button(:ptype, 1) %>
    <%= f.label(:ptype_numbers, "Numbers 0-99") %>
    <%= f.radio_button(:ptype, 2) %>
    <%= f.label(:ptype_cards, "Deck of Cards") %>

  </div>
  <br>
  <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/palaces/_peg.html.erb
<td>
  <%= submit_tag "#{digit}", :type => 'button', :class => "btn btn-info", :onclick => "window.location.href = '/famous_people/code/#{digit}'" %>
</td>
<% @palace.pegs.each do |peg| %>
    <% if peg.code == digit %>
        <td><%= peg.code %></td>
        <td><%= peg.place %></td>
        <td><%= peg.action %></td>
        <td><%= peg.link %></td>
        <td><%= peg.note %></td>

        <td><%= link_to 'Show', peg %></td>
        <td><%= link_to 'Edit', edit_peg_path(peg) %></td>
        <td><%= link_to 'Destroy', peg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
<% end %>

app/views/palaces/edit.html.erb
<h1>Editing Palace</h1>

<%= render 'form' %>

<%= link_to 'Show', @palace %> |
<%= link_to 'Back', palaces_path %>

app/views/palaces/index.html.erb
<h1>Palaces</h1>

<table class="table table-bordered table-striped table-hover">
  <tr>
    <th>Title</th>
    <th>Type</th>
    <th>Updated</th>
    <th></th>
  </tr>

<% @palaces.each do |palace| %>
  <tr>
    <td><%= palace.title %></td>
    <td><%= palace.ptype %></td>
    <td><%= palace.updated_at %></td>

    <td><%= link_to 'Show', palace %></td>
    <td><%= link_to 'Edit', edit_palace_path(palace) %></td>
    <td><%= link_to 'Destroy', palace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Palace', new_palace_path %>

app/views/palaces/new.html.erb
<h1>New Palace</h1>

<%= render 'form' %>

<%= link_to 'Back', palaces_path %>

app/views/palaces/show.html.erb
<br><br>
<p><h3><b>Memory Palace: </b></h3>
<h2>
  <%= @palace.title %>
</h2></p>


<% if @palace.ptype == 1 %>
    <p>

    </p>
    <div>
      <%= link_to "Add a Custom Peg", {:controller => "pegs", :action => "new", :palace_id => @palace.id }%>
    </div>
    <div>
      <%= link_to 'My Palaces', palaces_path %>
    </div>
    <br>
    <table class="table table-bordered table-striped table-hover">
      <tr>
        <th>Code</th>
        <th>Person</th>
        <th>Place</th>
        <th>Action</th>
        <th>Link</th>
        <th>Note</th>

      </tr>
      <tr>
        <% @digits.each do |digit| %>
          <tr>
            <td>
              <%= submit_tag "#{digit}", :type => 'button', :class => "btn btn-info", :onclick => "window.location.href = '/famous_people/addpeg/#{digit}'" %>
            </td>
            <% @palace.pegs.each do |peg| %>
                <% if peg.code == digit %>
                    <td><%= peg.full_name %></td>
                    <td><%= peg.place %></td>
                    <td><%= peg.action %></td>
                    <td><%= peg.link %></td>
                    <td><%= peg.note %></td>

                    <td><%= link_to 'Show', peg %></td>
                    <td><%= link_to 'Edit', edit_peg_path(peg) %></td>
                    <td><%= link_to 'Destroy', peg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            <% end %>
          </tr>
      <% end %>
      </tr>

    </table>

<% elsif @palace.ptype == 2 %>
        <p>
          <b>Cards:</b>
          <%= @palace.ptype %>
          <%= @palace.id %>

        </p>

<% end %>

<%= link_to "Add a Peg", {:controller => "pegs", :action => "new", :palace_id => @palace.id }%>

<br><br><br>

<script type="text/javascript">
    $('selector').fixedHeaderTable('show');
</script>






<%= link_to 'Edit', edit_palace_path(@palace) %> |
<%= link_to 'Back', palaces_path %>