config/routes.rb
Memorypalace::Application.routes.draw do

  resources :fish
  resources :famous_people
  resources :palaces
  resources :pegs

  authenticated :user do
    root :to => 'palaces#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :events

  match 'validate' => "home#validate"
  match "events/:id" => "events#update"

  match "famous_people" => "famous_people#index"
  match "famous_people/code/:code" => "famous_people#code"

  match "famous_people/addpeg/:code" => "famous_people#addpeg"

  match "pegs/add/:fp_id" => "pegs#add"

  match "contact_us" => "contact_us#index"

end

app/views/layouts/_carousel.html.erb
<% if current_page?(root_path) && !current_user %>

    <div class='carousel slide over-something' id='homepage-carousel'>
  <div class='carousel-inner slider-w'>
    <div class='active item'>
      <div class='container'>
        <h1 class='slider-header'>Build a <strong>Stronger</strong> memory with Memkazar.</h1>
        <h2 class='slider-sub-header'>Find Names and Ideas for your memory palaces.</h2>
        <div class='cta'>
          <a href="famous_people" class="btn btn-cta">Browse Names</a>
        </div>
        <div class='slider-browsers-w clearfix'>
          <div class='slider-browser slider-browser-left hidden-phone' data-position-bottom='-8%'>
            <img alt="Browser-window-1" src="assets/browser-window.png" />
          </div>
          <div class='slider-browser slider-browser-center' data-position-bottom='-9%'>
            <img alt="Browser-window-2" src="assets/browser-window.png" />
          </div>
          <div class='slider-browser slider-browser-right hidden-phone' data-position-bottom='-8%'>
            <img alt="Browser-window-3" src="assets/browser-window.png" />
          </div>
        </div>
      </div>
    </div>
    <div class='item'>
      <div class='container'>
        <h1 class='slider-header'>Build Your Memory Palace at Memkazar.</h1>
        <h2 class='slider-sub-header'>Find Names to Use In Your Memory Palace.</h2>
        <div class='cta'>
          <a href="users/sign_in" class="btn btn-cta btn-warning">Build a Memory Palace</a>
        </div>
        <div class='row zoomed-browsers-w'>
          <div class='span4'>
            <div class='zoomed-browser'>
              <img alt="Browser-window-1" src="assets/browser-window.png" />
            </div>
          </div>
          <div class='span4'>
            <div class='zoomed-browser hidden-phone'>
              <img alt="Browser-window-2" src="assets/browser-window.png" />
            </div>
          </div>
          <div class='span4'>
            <div class='zoomed-browser hidden-phone'>
              <img alt="Browser-window-3" src="assets/browser-window.png" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <a class='carousel-control left' data-slide='prev' href='#homepage-carousel'>
    <i class='icon-chevron-left'></i>
  </a>
  <a class='carousel-control right' data-slide='next' href='#homepage-carousel'>
    <i class='icon-chevron-right'></i>
  </a>
</div>

<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "MemKazar", root_path, :class => 'brand' %>
<div id="top-navigation" class="nav-collapse subnav-collapse pull-right">
  <ul class="nav">
  <% if user_signed_in? %>
      <li>
        <%= link_to('Famous People', famous_people_path)  %>
      </li>
      <li>
      </li>
      <li>
      </li>
  <% else %>

      <li>
        <%= link_to('Browse Names', famous_people_path)  %>
      </li>
      <li>
      </li>
    <% end %>
  <% if user_signed_in? %>
      <li>
        <%= link_to('Edit account', edit_user_registration_path) %>
      </li>
      <% if current_user.has_role? :admin %>
          <li>
            <%= link_to('Admin', users_path) %>
          </li>
      <% end %>
   </ul>
  <% else %>
      <li>
        <%= link_to('Contact Us', contact_us_path)  %>
      </li>
    </ul>

        <div class="top-account-control visible-desktop">
          <%= link_to "Create Account", new_user_registration_path, :class => "top-create-account" %>
          <%= link_to "Sign In", new_user_session_path, :class => "top-sign-in" %>
          <div class="login-box">
            <a class="close login-box-close" href="#">×</a>
            <h4 class="login-box-head">Login Form</h4>
            <div class="control-group">
              <label>Username</label>
              <input class="span2" type="text" placeholder="Input username...">
            </div>
            <div class="control-group">
              <label>Password</label>
              <input class="span2" type="text" placeholder="Input password...">
            </div>
            <div class="login-actions">
              <button class="btn btn-primary">Log Me In</button>
            </div>
          </div>
        </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Memkazar" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Add Google Web Fonts support -->
    <link href="http://fonts.googleapis.com/css?family=Abel:400|Oswald:300,400,700" media="all" rel="stylesheet" type="text/css" >


  </head>
  <body>
  <header id='header'>
    <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
  </div>
 </header>
  <%= render 'layouts/carousel' %>
  <section class="section-wrapper stripped">
    <div>
      <div class="row">
        <div class="span4"></div>
        <div class="span3"></div>
        <div class="span3"></div>
        <% if user_signed_in? %>
          <div class="span1"> <%= current_user.name %></div>
          <div class="span1"><%= button_to('Logout', destroy_user_session_path, :method => :delete) %>
          </div>
        <% else %>
          <div class="span2"></div>
        <% end %>
          <br>
      </div>
    <div class="container">
      <div>
        <div>
          <div>
            <%= render 'layouts/messages' %>
          </div>
        </div>
        <%= yield %>
        <footer>
        </footer>
        <!-- Start of StatCounter Code for Default Guide -->
        <script type="text/javascript">
            var sc_project=9413181;
            var sc_invisible=1;
            var sc_security="4042a06e";
            var scJsHost = (("https:" == document.location.protocol) ?
                    "https://secure." : "http://www.");
            document.write("<sc"+"ript type='text/javascript' src='" +
                    scJsHost+
                    "statcounter.com/counter/counter.js'></"+"script>");
        </script>
        <noscript><div class="statcounter"><a title="website
statistics" href="http://statcounter.com/"
                                              target="_blank"><img class="statcounter"
                                                                   src="http://c.statcounter.com/9413181/0/4042a06e/1/"
                                                                   alt="website statistics"></a></div></noscript>
        <!-- End of StatCounter Code for Default Guide -->
      </div>
    </div> <!--! end of .container -->
  </div> <!--! end of #main -->
  </section>
  </body>
</html>