config/routes.rb
Memorypalace::Application.routes.draw do

  resources :fish
  resources :famous_people
  resources :palaces
  resources :pegs

  authenticated :user do
    root :to => 'palaces#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :events

  match 'validate' => "home#validate"
  match "events/:id" => "events#update"

  match "famous_people" => "famous_people#index"
  match "famous_people/code/:code" => "famous_people#code"

  match "famous_people/addpeg/:code" => "famous_people#addpeg"

  match "pegs/add/:fp_id" => "pegs#add"

  match "contact_us" => "contact_us#index"

end

app/models/fish.rb
class Fish < ActiveRecord::Base
  attr_accessible :desc, :name
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  # GET /fish
  # GET /fish.json
  def index
    @fish = Fish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
    @fish = Fish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/new
  # GET /fish/new.json
  def new
    @fish = Fish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/1/edit
  def edit
    @fish = Fish.find(params[:id])
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(params[:fish])

    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fish, notice: 'Fish was successfully created.' }
        format.json { render json: @fish, status: :created, location: @fish }
      else
        format.html { render action: "new" }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fish/1
  # PUT /fish/1.json
  def update
    @fish = Fish.find(params[:id])

    respond_to do |format|
      if @fish.update_attributes(params[:fish])
        format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish = Fish.find(params[:id])
    @fish.destroy

    respond_to do |format|
      format.html { redirect_to fish_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= simple_form_for(@fish) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="input-xlarge">
    <%= f.input :desc %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fish/edit.html.erb
<h1>Editing fish</h1>

<%= render 'form' %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/index.html.erb
<h1>Listing fish</h1>

<table class="table table-bordered table-striped table-hover">
  <tr>
    <th>Name</th>
    <th></th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fish.each do |fish| %>
  <tr>
    <td><%= fish.name %></td>
    <td><%= fish.desc %></td>
    <td><%= link_to 'Show', fish %></td>
    <td><%= link_to 'Edit', edit_fish_path(fish) %></td>
    <td><%= link_to 'Destroy', fish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fish', new_fish_path %>

app/views/fish/new.html.erb
<h1>New fish</h1>

<%= render 'form' %>

<%= link_to 'Back', fish_index_path %>

app/views/fish/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fish.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @fish.desc %>
</p>


<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>